command: python
env:
  base:
  - {image: ubuntu:16.04, pkg-manager: apt}
  - {image: centos:7, pkg-manager: apt}
  fsl:
  - {version: 5.0.9}
  - {version: 5.0.10}
  miniconda:
  - {conda_install: [python=3.5, nipype, pandas, requests]}
inputs:
- [string, --key, 11an55u9t2TAf0EV2pHN0vOd8Ww2Gie-tHp9xGULh_dA]
- [int, -n, '3']
script: run_demo_workflow.py
tests:
- file: [output/AnnArbor_sub16960/segstats.json, output/AnnArbor_sub20317/segstats.json,
    output/AnnArbor_sub38614/segstats.json]
  name: regr
  script: check_output.py
