command: python
env:
  base:
  - {image: debian:stretch, pkg-manager: apt}
  - {image: ubuntu:16.04, pkg-manager: apt}
  miniconda:
  - {conda_install: python=3.5}
  - {conda_install: python=2.7}
inputs:
- [File, -f, list2sort.json]
script: sorting.py
tests:
- {file: list_sorted.json, name: regr1, script: test_obj_eq.py}
- {file: sum_list.json, name: regr2, script: test_obj_eq.py}
- {file: list_sorted.json, name: stat, script: stat_list.py}

